export enum TokenType {
    IDENTIFIER = "IDENTIFIER",
    KEYWORD = "KEYWORD",
    STRING = "STRING",
    NUMBER = "NUMBER",
    OPERATOR = "OPERATOR",
    PUNCTUATION = "PUNCTUATION",
    NEWLINE = "NEWLINE",
    TIMESTAMP = "TIMESTAMP",
    DURATION = "DURATION",
    DATE = "DATE",
    COMMENT = "COMMENT",
    UNKNOWN = "UNKNOWN"
}